version: '3'

services:
  social_app:
    build: .
    image: python:3.6
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/code
    ports:
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - migration

  migration:
    image: python:3.6
    command: python manage.py migrate --noinput
    volumes:
      - .:/app/code

